spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/payment_schema
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  spring:
    mvc:
      throw-exception-if-no-handler-found: false

server:
  port: 8080